name: Custom Contribution Snake

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate custom snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: ${{ github.repository_owner }}
        run: |
          python scripts/generate_snake.py

      - name: Publish animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
